"""tab_name_change

Revision ID: 40938b3ee843
Revises: 7d07c904c16f
Create Date: 2022-09-16 17:02:42.410912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40938b3ee843'
down_revision = '7d07c904c16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pname')
    )
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey'),
    sa.UniqueConstraint('pname', name='people_pname_key')
    )
    op.drop_table('tbl_people')
    # ### end Alembic commands ###
